version: '3.7'
services:
    nzedb-container:
        build: .
        stdin_open: true
        tty: true
        volumes:
            - ${PWD}/nzedb_data:/var/www/nZEDb
        #    - ${PWD}/nzedb_db:/
        container_name: nzedb-container
        image: nzedb-image

