version: '3.7'
services:
    nzedb-container:
        build: .
        stdin_open: true
        tty: true
        ports:
          - 8000:80
#        volumes:
#            - ${PWD}/nzedb_data:/var/www/nZEDb
#            - ${PWD}/nzedb_db:/var/lib/mysql
        container_name: nzedb-container
        image: nzedb-image

